name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install --force && CI=false npm run build
    - run: docker build -t nuskusa .
    - run: docker tag nuskusa:latest nuskusa/nuskusa:latest
    - run: docker login --username=nuskusa --password=${{ secrets.DOCKER_PASSWORD }}
    - run: docker push nuskusa/nuskusa:latest
    - uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
    - id: CodeDeploy
      uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
      with:
          application: nuskusa
