name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install --force && CI=false npm run build
    - run: docker build -t nuskusa .
    - run: docker tag nuskusa:latest kjaehyeok21/nuskusa:latest
    - run: docker push kjaehyeok21/nuskusa:latest
