name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
env: 
  REACT_APP_API_KEY: '${{ secrets.REACT_APP_API_KEY }}'
  REACT_APP_APP_ID: '${{ secrets.REACT_APP_APP_ID }}'
  REACT_APP_AUTH_DOMAIN: '${{ secrets.REACT_APP_AUTH_DOMAIN }}'
  REACT_APP_MESSAGING_SENDER_ID: '${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}'
  REACT_APP_PROJECT_ID: '${{ secrets.REACT_APP_PROJECT_ID }}'
  REACT_APP_STORAGE_BUCKET: '${{ secrets.REACT_APP_STORAGE_BUCKET }}'
  REACT_APP_HOST: '${{ secrets.REACT_APP_HOST }}'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install --force && CI=false npm run build
    - run: docker build -t nuskusa .
    - run: docker tag nuskusa:latest nuskusa/nuskusa:latest
    - run: docker login --username=nuskusa --password=${{ secrets.DOCKER_PASSWORD }}
    - run: docker push nuskusa/nuskusa:latest
    - name: trigger jenkins nuskusa job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://nuskoreasociety.org:8000"
        user: "nuskusa-admin"
        token: "nuskusac_cicd"
        job: "nuskusa"
