name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install --force && CI=false npm run build
    - name: AWS ECR
      uses: kciter/aws-ecr-action@v4
      with:
        access_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        account_id: "${{ secrets.AWS_ACCOUNT_ID }}"
        repo: "nuskusa"
        region: "ap-southeast-1"
        tags: "latest"
        
